<?xml version="1.0" encoding="utf-8"?><Database Name="HumCase" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.cases" Member="cases">
    <Type Name="case">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="response_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_by_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_to_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="responsible_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estimated_hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estimated_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="reference" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="part_of_contract" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="feedback_required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="checklist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="release_solution" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="test_flow" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="releasedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="layer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isinvoicable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isupdated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="solution_confirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="verified_by_developer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estimate_Text" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="estimate_accepted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estimate_released" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="stateid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="releasePlanid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isClientNetCase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="productid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionHTML" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Versionid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnvironmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sReleaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="threshold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="estimated_delivery_hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estimated_delivery_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="public_summary" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="shortname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="identified_branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="technical_summary" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="lastcommit_branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="breaking_change" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="specification_accepted" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estimation_finalized" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="exclude_case" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="roadmap_new_report" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dev_estimate" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="case_case_history" Member="case_histories" ThisKey="id" OtherKey="case_id" Type="case_history" />
    </Type>
  </Table>
  <Table Name="dbo.branches" Member="branches">
    <Type Name="branch">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="svn_path" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="freeze_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="release_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="reserved_hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sort_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="target_branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WebConfiguration" Member="WebConfigurations">
    <Type Name="WebConfiguration">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Parameter" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.builds" Member="builds">
    <Type Name="build">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="revision" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="started_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="previous_build_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.case_comments" Member="case_comments">
    <Type Name="case_comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="internal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="readby_supplier" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="readby_customer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="solution" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="second_level" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="external_transfered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="transfered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.case_estimate_types" Member="case_estimate_types">
    <Type Name="case_estimate_type">
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Factor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsInternal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.case_estimates_values" Member="case_estimates_values">
    <Type Name="case_estimates_value">
      <Column Name="estimateTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estimateValue" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="estimateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="estimateTypeText" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="estimateTypeCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="estimateCaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.case_history" Member="case_histories">
    <Type Name="case_history">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="casecomment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="external_transfered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="case_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="case_case_history" Member="case" ThisKey="case_id" OtherKey="id" Type="case" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.case_layer" Member="case_layers">
    <Type Name="case_layer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.case_subscriptions" Member="case_subscriptions">
    <Type Name="case_subscription">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.case_transfers" Member="case_transfers">
    <Type Name="case_transfer">
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="old_case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Case_Type" Member="Case_Types">
    <Type Name="Case_Type">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.case_user_views" Member="case_user_views">
    <Type Name="case_user_view">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viewdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="viewcount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CaseHelp" Member="CaseHelps">
    <Type Name="CaseHelp">
      <Column Name="CasehelpId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pageid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Linkid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Heading" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CaseLog" Member="CaseLogs">
    <Type Name="CaseLog">
      <Column Name="Log_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Log_Case_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Log_Username" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Log_CurrentPage" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Log_RemoteIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Log_ViewDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Log_Text" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.casesClientNet" Member="casesClientNets">
    <Type Name="casesClientNet">
      <Column Name="CaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CaseProductid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseReleaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseCreatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CaseDeadline" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CaseCreatorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseCreatorCustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseCreatorlocalPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseCreatorDirectPhone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseCreatorMobilphone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseCreatorEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseCCmail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CaseCreatorIpadress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseTitle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CaseDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CaseInternalNote" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CaseResponsibleid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseRessourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseExternalCaseHandlerid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseSolutionTime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CaseStateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseStateLastActionDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CaseUsedDevelopmentTime" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CaseSalesOfferid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseRandomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseSeverityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseReleaseplanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseReleaseTypeid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseTypeid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseRefId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Transfer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExternalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseShared" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sReleaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseEnvironmentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CaseRessourceName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CaseSolutionDateFrom" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CaseSolutionDateTo" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfirmSolution" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ConfirmedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ConfirmedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsInvoiceble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Layer" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CaseStats" Member="CaseStats">
    <Type Name="CaseStat">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IntValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.change_revision_reviews" Member="change_revision_reviews">
    <Type Name="change_revision_review">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="revision" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="review_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="comment" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.change_revisions" Member="change_revisions">
    <Type Name="change_revision">
      <Column Name="revision" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logged_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="meta" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="review" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="review_assigned_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="review_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.changelog_item_overrides" Member="changelog_item_overrides">
    <Type Name="changelog_item_override">
      <Column Name="revision" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="from_case_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="to_case_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.changelog_items" Member="changelog_items">
    <Type Name="changelog_item">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="revision" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logged_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Computers" Member="Computers">
    <Type Name="Computer">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MacAddress" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="LastSeen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contract_finance" Member="Contract_finances">
    <Type Name="Contract_finance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractHours" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ContractPriceHour" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="UsedHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPriceHour" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ContractName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.customers" Member="customers">
    <Type Name="customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="notification" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExtraordinaryPatch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProactivityEmail" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultCaseStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ultrahigh_emails" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="integration_code" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="live_branch" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="target_branch" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="customer_responsible" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Environment" Member="Environments">
    <Type Name="Environment">
      <Column Name="Environmentid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnvironmentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.erp_connection" Member="erp_connections">
    <Type Name="erp_connection">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customers_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ERP_account" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockAccount" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastExported" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.erp_pricelist" Member="erp_pricelists">
    <Type Name="erp_pricelist">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customers_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="validfrom" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="validto" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="currency" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="discount" Type="System.Decimal" DbType="Decimal(9,0) NOT NULL" CanBeNull="false" />
      <Column Name="remark" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.erp_pricelist_entry" Member="erp_pricelist_entries">
    <Type Name="erp_pricelist_entry">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="erp_pricelist_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="netrate" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="discount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="rate" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="user_roles_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.events" Member="events">
    <Type Name="event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reference_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="executed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="launch" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="error_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XmlData" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.file_binaries" Member="file_binaries">
    <Type Name="file_binary">
      <Column Name="file_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="binary_content" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.file_bindings" Member="file_bindings">
    <Type Name="file_binding">
      <Column Name="file_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ref_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.file_extensions" Member="file_extensions">
    <Type Name="file_extension">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="extension" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.files" Member="files">
    <Type Name="file">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="filename" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="contenttype" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="filesize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="transfered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.forums" Member="forums">
    <Type Name="forum">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.HumTrace" Member="HumTraces">
    <Type Name="HumTrace">
      <Column Name="Traceid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Createddate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.invoices" Member="invoices">
    <Type Name="invoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_hours" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.knowledgebase_categories" Member="knowledgebase_categories">
    <Type Name="knowledgebase_category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.knowledgebase_customers" Member="knowledgebase_customers">
    <Type Name="knowledgebase_customer">
      <Column Name="question_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.knowledgebase_questions" Member="knowledgebase_questions">
    <Type Name="knowledgebase_question">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="answer" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.milestone_cases" Member="milestone_cases">
    <Type Name="milestone_case">
      <Column Name="milestone_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.milestone_users" Member="milestone_users">
    <Type Name="milestone_user">
      <Column Name="milestone_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.milestones" Member="milestones">
    <Type Name="milestone">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="validfrom" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="validto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="createdby" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="assigned_to_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="specification_launch" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="specification_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="specification_end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="development_launch" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="development_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="development_end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nis_testing_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="nis_testing_end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="customer_testing_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="customer_testing_end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="delivery_deadline" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="theme" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="specification_launch_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="specification_period_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="development_period_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="development_launch_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="nis_testing_period_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="customer_testing_period_planned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.page_log" Member="page_logs">
    <Type Name="page_log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="page_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PageData" Member="PageDatas">
    <Type Name="PageData">
      <Column Name="Pageid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PageTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PageContent" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PageLastEditor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PageLastEditorDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Parentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RootParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Href" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Target" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="show" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccessRole" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Menuitem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageTemplate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pages" Member="pages">
    <Type Name="page">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="handle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Proactivity" Member="Proactivities">
    <Type Name="Proactivity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Caseid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleasePlanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DirectionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Createddate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProActivityText" Member="ProActivityTexts">
    <Type Name="ProActivityText">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Directionid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.product_groups" Member="product_groups">
    <Type Name="product_group">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_hooks" Member="product_hooks">
    <Type Name="product_hook">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="major_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_versions" Member="product_versions">
    <Type Name="product_version">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="major_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="major" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="minor" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.products" Member="products">
    <Type Name="product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="latest_version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="testing_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="group_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commercialname" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="parentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accessrole" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imageSmall" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imageMedium" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.project_list_exclusions" Member="project_list_exclusions">
    <Type Name="project_list_exclusion">
      <Column Name="project_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="list_name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.projects" Member="projects">
    <Type Name="project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="startdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="enddate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="main_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="country" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="customer_contact_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="auto_milestone_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Contract_Finance_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QualificationGroup_Customers" Member="QualificationGroup_Customers">
    <Type Name="QualificationGroup_Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="group_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QualificationGrp" Member="QualificationGrps">
    <Type Name="QualificationGrp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.release_cases" Member="release_cases">
    <Type Name="release_case">
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.release_customers" Member="release_customers">
    <Type Name="release_customer">
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.release_files" Member="release_files">
    <Type Name="release_file">
      <Column Name="file_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.release_milestones" Member="release_milestones">
    <Type Name="release_milestone">
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="milestone_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.release_products" Member="release_products">
    <Type Name="release_product">
      <Column Name="release_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ReleaseContent" Member="ReleaseContents">
    <Type Name="ReleaseContent">
      <Column Name="ContentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customerid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Releaseplanid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Createdby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Emailed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ContentFile" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContentFileName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ContentFileType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContentFileSize" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.releasefiles_clientnet" Member="releasefiles_clientnets">
    <Type Name="releasefiles_clientnet">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReleaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleasePatchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseFileCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseFileName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ReleaseFileType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ReleaseFileSize" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ReleaseFile" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.releasePlan" Member="releasePlans">
    <Type Name="releasePlan">
      <Column Name="ReleasePlanId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReleaseText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReleaseNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Releasedate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ExpireCustomerDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ExpireDevelopmentDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ShowOnPlan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.releases" Member="releases">
    <Type Name="release">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="testing_user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="testing_case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="revision" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="readme" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="external_transfered" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subversion_url" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.releases_clientnet" Member="releases_clientnets">
    <Type Name="releases_clientnet">
      <Column Name="Releaseid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReleasePlanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Productid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseCharacterId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iversion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ReleaseNotes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Released" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReleasedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ReleasedBy" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SignOff" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReleaseType" Member="ReleaseTypes">
    <Type Name="ReleaseType">
      <Column Name="ReleaseTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseTypeText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Severity" Member="Severities">
    <Type Name="Severity">
      <Column Name="Severityid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeverityText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.state" Member="states">
    <Type Name="state">
      <Column Name="StateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StateLocation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StateImage" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StateActionDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StatusText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaskLog" Member="TaskLogs">
    <Type Name="TaskLog">
      <Column Name="LogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="EntryTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EntryType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TaskParameters" Member="TaskParameters">
    <Type Name="TaskParameter">
      <Column Name="ParentTask" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XmlParameters" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Task_TaskParameter" Member="Task" ThisKey="ParentTask" OtherKey="TaskId" Type="Task" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Creator" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JobType" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RetryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastRun" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastResult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NextRunTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaxRunTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BeginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StartHour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartMinute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerFlags" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerData1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerData2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerData3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Task_TaskParameter" Member="TaskParameters" ThisKey="TaskId" OtherKey="ParentTask" Type="TaskParameter" />
    </Type>
  </Table>
  <Table Name="dbo.time_registrations" Member="time_registrations">
    <Type Name="time_registration">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="remark" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="hours" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="chargeable_hours" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="invoiced_hours" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="invoice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="second_level" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="registration_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="created_by_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="updated_by_userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_case_bookmarks" Member="user_case_bookmarks">
    <Type Name="user_case_bookmark">
      <Column Name="case_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_role_links" Member="user_role_links">
    <Type Name="user_role_link">
      <Column Name="role_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_roles" Member="user_roles">
    <Type Name="user_role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_teams" Member="user_teams">
    <Type Name="user_team">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Manager_User_link_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.user_types" Member="user_types">
    <Type Name="user_type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="mobilephone" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="notification_method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DomainAccount" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PendingDevelopment" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QualificationGrp_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="default_role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetPct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="countrycode" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="useproxy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Team_link_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserStats" Member="UserStats">
    <Type Name="UserStat">
      <Column Name="WeekNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ClosedInWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpenInWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalOpen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reflux" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeOffCases" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeOff" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Invoiceable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IllnessHours" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="VacationHours" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>